// Style Dictionary config that turns design/tokens/tokens.json into
// src/styles/tokens.css. Run via `npm run build:tokens`; CI fails the build
// if the committed tokens.css doesn't match this file's output
// (.github/workflows/ci.yml, mirroring the generated-API-client staleness
// check at the same file).
//
// No transforms are registered on purpose: every token's $value is already
// exactly what the CSS custom property should read (a px length, a hex
// colour, an rgba() string, a font-family stack, a shadow list), and every
// leaf key in tokens.json is already the custom-property name minus "--"
// (see design/docs/principles.md — components reference the terse names
// directly, e.g. var(--ink-2), so the generator must reproduce them
// byte-for-byte rather than deriving a longer namespaced name).
//
// The custom "css/ims-tokens" format hand-lays-out :root and
// [data-theme="dark"] to match the file's previous hand-written structure
// exactly, including its section comments — those comments are presentation,
// not token data, so they live here rather than in tokens.json.

/**
 * Look up tokens by full path (e.g. ["color", "light", "bg"]) rather than by
 * leaf name alone — "bg", "ink", etc. exist once under color.light and once
 * under color.dark, so a name-only lookup would collide the two themes.
 *
 * @param {Map<string, {$value: string}>} byPath
 * @param {string[]} prefix
 * @param {string[]} names
 * @returns {string}
 */
function lines(byPath, prefix, names) {
  return names
    .map((name) => {
      const token = byPath.get([...prefix, name].join("/"));
      if (!token) {
        throw new Error(
          `design/tokens/tokens.json is missing "${[...prefix, name].join(".")}"`,
        );
      }
      return `  --${name}: ${token.$value};`;
    })
    .join("\n");
}

const SPACING = ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"];
const RADIUS = ["r-sm", "r", "r-lg", "r-full"];
const FONT = ["sans", "tight", "mono"];
const FONT_SIZE = ["fs-0", "fs-1", "fs-2", "fs-3", "fs-4", "fs-5", "fs-6", "fs-7", "fs-8", "fs-9"];
const LINE_HEIGHT = ["lh-tightest", "lh-tight", "lh", "lh-loose", "lh-box"];
const FONT_WEIGHT = ["fw", "fw-med", "fw-bold"];
const Z_INDEX = [
  "z-icon",
  "z-sticky",
  "z-results",
  "z-mobile-nav",
  "z-menu",
  "z-listbox",
  "z-toast",
  "z-modal",
  "z-skiplink",
];
const COLOR = [
  "bg",
  "sunken",
  "fill",
  "fill-2",
  "line",
  "line-2",
  "ink",
  "ink-2",
  "ink-3",
  "ink-4",
  "accent",
  "accent-soft",
  "accent-line",
  "pos",
  "pos-soft",
  "pos-line",
  "warn",
  "warn-soft",
  "warn-line",
  "neg",
  "neg-soft",
  "neg-line",
  "btn",
  "btn-h",
  "btn-ink",
  "row-warn",
  "row-neg",
  "skel",
  "skel-hi",
  "ring-1",
  "ring-2",
  "ring-3",
];
const ELEVATION = ["sh-1", "sh-2", "ring"];

const HEADER = `/*
 * Design tokens — generated by Style Dictionary from design/tokens/tokens.json
 * (\`npm run build:tokens\`; CI checks this file isn't stale). Do not hand-edit
 * this file — edit tokens.json and regenerate. Names match the legacy
 * prototype this design system replaced, not always a doc's prose (e.g.
 * --btn-h not --btn-hover; --row-warn/--row-neg aren't descriptive names).
 *
 * These are bare custom properties, not namespaced into Tailwind's \`@theme\`
 * (\`--color-*\`, \`--spacing-*\`, ...). Every component in src/components/ui/
 * references these directly via CSS Modules using var(--token) — namespacing
 * them for Tailwind utility generation would mean either duplicating every
 * value under two names or components not matching their reference styling
 * byte-for-byte. Page-layout work references these same variables directly
 * (inline style or a CSS module) rather than through generated Tailwind
 * utility classes; add an \`@theme inline\` bridge layer then, if a concrete
 * need for Tailwind-utility access shows up — not speculatively now.
 *
 * Light is always the default on load, never prefers-color-scheme-detected.
 * There is deliberately no \`@media (prefers-color-scheme: dark)\` block here
 * — only the explicit [data-theme="dark"] override, set by the theme toggle
 * (src/components/shell/ThemeToggle.tsx) and persisted to localStorage.
 */`;

/** @type {import('style-dictionary/types').Config} */
const config = {
  source: ["design/tokens/tokens.json"],
  usesDtcg: true,
  // Every color/elevation leaf name (e.g. "bg", "sh-1") exists once under
  // .light and once under .dark by design — Style Dictionary's many-to-one
  // name-collision warning is a false positive here, not a real conflict.
  log: { warnings: "disabled" },
  hooks: {
    formats: {
      "css/ims-tokens": ({ dictionary }) => {
        const byPath = new Map(dictionary.allTokens.map((token) => [token.path.join("/"), token]));

        const root = [
          "  /* spacing — 4px base, the only values allowed */",
          lines(byPath, ["spacing"], SPACING),
          "  /* radius */",
          lines(byPath, ["radius"], RADIUS),
          '  /* type — next/font/google\'s generated variables (src/styles/fonts.ts), not\n     a Google Fonts @import */',
          lines(byPath, ["font"], FONT),
          "  /* type scale — every font-size in the product collapses to these 10 steps */",
          lines(byPath, ["fontSize"], FONT_SIZE),
          "  /* line height — unitless except lh-box, which matches a fixed single-line\n     box height (kbd hint, select option row), not body copy */",
          lines(byPath, ["lineHeight"], LINE_HEIGHT),
          "  /* font weight — the only three in use */",
          lines(byPath, ["fontWeight"], FONT_WEIGHT),
          "  /* colour — light (default) */",
          lines(byPath, ["color", "light"], COLOR),
          "  /* elevation — two levels, no more */",
          lines(byPath, ["elevation", "light"], ELEVATION),
          "  /* stacking order, low to high */",
          lines(byPath, ["zIndex"], Z_INDEX),
          `  --dur: ${byPath.get("motion/dur").$value};`,
          `  --dur-slow: ${byPath.get("motion/dur-slow").$value};`,
          `  --dur-step: ${byPath.get("motion/dur-step").$value};`,
          `  --ease-out: cubic-bezier(${byPath.get("motion/ease-out").$value.join(", ")});`,
        ].join("\n");

        const dark = [
          "  color-scheme: dark;",
          lines(byPath, ["color", "dark"], COLOR),
          lines(byPath, ["elevation", "dark"], ELEVATION),
        ].join("\n");

        return `${HEADER}\n\n:root {\n${root}\n}\n\n[data-theme="dark"] {\n${dark}\n}\n`;
      },
    },
  },
  platforms: {
    css: {
      transforms: [],
      buildPath: "dist/",
      files: [
        {
          destination: "tokens.css",
          format: "css/ims-tokens",
        },
      ],
    },
  },
};

export default config;
